language: node_js
node_js:
  - '4'

env:
  global:
    - CI=true
    # the following are set via travis admin panel
    # ES_HOST
    # AWS_KEY
    # AWS_SECRET

before_install:
  - npm install -g serverless@beta
  - mkdir -p ~/.aws
  - echo '$ES_HOST' > .env
  - echo '[default]' > ~/.aws/credentials
  - echo 'aws_access_key_id='"$AWS_KEY"'' >> ~/.aws/credentials
  - echo 'aws_secret_access_key='"$AWS_SECRET"'' >> ~/.aws/credentials

install:
  - npm install

script:
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: serverless deploy
  on:
    branch:
      - master
