language: node_js
node_js:
  - "4"

before_install:
  - npm install -g serverless@0.5.3

install:
  - npm install
  - npm run build
  - npm run devseed -- -p travis
  - sed -i -e 's/localhost:9200/'"$ES_HOST"'/' _meta/variables/s-variables-common.json

script:
  - cd sat && sls function run

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] &&
     [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "This will deploy!"
  else
    echo "This will not deploy!"
  fi
