language: node_js
node_js:
  - "4"

before_install:
  - npm install -g serverless@0.5.3
  - mkdir -p ~/.aws
  - echo '[travis]' > ~/.aws/credentials
  - echo 'aws_access_key_id = '"$AWS_KEY"'' >> ~/.aws/credentials
  - echo 'aws_secret_access_key = '"$AWS_SECRET"'' >> ~/.aws/credentials
  - cat ~/.aws/credentials

install:
  - npm install
  - npm run build
  - sls project init init -s dev -r us-east-1 -c -p devseed
  - sed -i -e 's/sat-api"/sat-api", "es_host": "'"$ES_HOST"'"/' _meta/variables/s-variables-common.json
  - cat _meta/variables/s-variables-common.json

script:
  - cd sat && sls function run

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] &&
     [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "This will deploy!"
  else
    echo "This will not deploy!"
  fi

